# nodeport-service.yml
apiVersion: v1
kind: Service
metadata:
  name: examen-service
  namespace: bartdewa-examen
spec:
  type: NodePort
  selector:
    app: examen-app
  ports:
    - name: api-port
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000
    - name: frontend-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001


